### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-irrigation#1]
How many zone will be possible to use?

**Comment by maccoylton** [comment]
At the moment 1 , when I get some spare time I plan to add more

**Comment by toshibochan** [comment]
Hope soon you can add all available gpio pin.

**Comment by dachoeks3** [comment]
Any updates on more zones? Thanks

**Comment by maccoylton** [comment]
I have added a pre release that adds a second valve, please try out and provide feedback, more to come as time permits

**Comment by dachoeks3** [comment]
> I have added a pre release that adds a second valve, please try out and provide feedback, more to come as time permits

I'll try it this weekend. Thanks

**Comment by dachoeks3** [comment]
Sorry, where is this pre release located? 

Got it.. it's in releases lol
